apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replias: 3
  selector: 
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: twentyfourtyeight
        image: lazypower/2048
      ports:
        - containerPort: 80